import { describe, expect, it } from 'vitest';
import { applyBulkEdit, filterAndSortCards, formatSynonyms, parseSynonyms, updateCardFromForm, type EditorCard } from '../src/card-editor-domain';
import type { Catalog } from '../src/model';

const card=(id:string,topic='B',status:EditorCard['status']='draft'):EditorCard=>({id,version:1,status,topicId:topic,examQuestion:'',prompt:`Prompt ${id}`,points:1,difficulty:2,tags:[],questionType:'multiple_choice',answer:{modelAnswer:'Answer',requiredTerms:[],choices:[{id:'a',text:'A',correct:true},{id:'b',text:'B'}]},assetRefs:[{assetId:'asset-1',role:'prompt'}],source:'Script',changedAt:'2026-08-01T00:00:00.000Z'});

describe('full card editor domain',()=>{
  it('parses and formats per-card synonyms',()=>{const parsed=parseSynonyms('PCR => Polymerase chain reaction, PCR-Test\nDNA => Desoxyribonukleinsäure');expect(parsed.PCR).toEqual(['Polymerase chain reaction','PCR-Test']);expect(formatSynonyms(parsed)).toContain('DNA => Desoxyribonukleinsäure');});
  it('filters and sorts by status/type/topic/query',()=>{const cards=[card('b','T2','released'),card('a','T1','draft'),card('c','T1','draft')];cards[2].questionType='cloze';expect(filterAndSortCards(cards,{status:'draft',topic:'T1',questionType:'multiple_choice',sort:'id'}).map(c=>c.id)).toEqual(['a']);expect(filterAndSortCards(cards,{query:'Prompt c',sort:'id'}).map(c=>c.id)).toEqual(['c']);});
  it('preserves structured answer fields and assets when saving basic form fields',()=>{const existing=card('x');const form=new FormData();for(const [k,v] of Object.entries({id:'x',status:'draft',topicId:'New',examQuestion:'Q1',prompt:'Changed',points:'2',difficulty:'3',tags:'one, two',questionType:'multiple_choice',modelAnswer:'Changed answer',requiredTerms:'term',value:'',tolerance:'0',source:'Book',sourcePage:'12',changeReason:'edit',editorSynonyms:'term => alias',editorTypoEnabled:'on',editorTypoDistance:'2',editorSourceKind:'book',editorSourceTitle:'Title',editorSourceUrl:'https://example.com',editorSourceSection:'Ch 2',editorSourceAccessedAt:'2026-08-04'}))form.set(k,v);const next=updateCardFromForm(existing,form,new Date('2026-08-04T10:00:00Z'));expect(next.answer.choices).toEqual(existing.answer.choices);expect(next.assetRefs).toEqual(existing.assetRefs);expect(next.answer.synonyms).toEqual({term:['alias']});expect(next.answer.typoTolerance).toEqual({enabled:true,maxDistance:2});expect(next.sourceMeta).toMatchObject({kind:'book',title:'Title'});});
  it('bulk edits selected cards only',()=>{const catalog:Catalog={catalogId:'c',title:'C',version:'1',createdAt:'',updatedAt:'',cards:[card('a'),card('b')]};const next=applyBulkEdit(catalog,new Set(['b']),{status:'in_review',topicId:'New',addTag:'bulk'},new Date('2026-08-04T10:00:00Z'));expect(next.cards[0].status).toBe('draft');expect(next.cards[1]).toMatchObject({status:'in_review',topicId:'New'});expect(next.cards[1].tags).toContain('bulk');});
});
