import type { CardVersion } from './model';

const at = '2026-07-25T14:30:00.000Z';
const source = 'Fuegetechnikskript_SoSe2026.pdf / Gedächtnisprotokoll Fügetechnik SS24';
const card = (id:string, topicId:string, examQuestion:string, prompt:string, modelAnswer:string, requiredTerms:string[]=[], points=2, questionType:CardVersion['questionType']='free_text'):CardVersion => ({
  id:`ft${id}`, version:1, status:'released', topicId, examQuestion, prompt, points,
  difficulty:3, tags:['prüfung-ss24'], questionType, answer:{modelAnswer, requiredTerms}, source, changedAt:at,
  changeReason:'Ergänzung der nicht bildabhängigen Prüfungsinhalte 12–45'
});

export const additionalFuegetechnikCards:CardVersion[] = [
  card('1201','Schweißgrundlagen','12','Welche drei Einflussgrößen bilden das schweißtechnische Dreieck?','Werkstoff, Konstruktion und Fertigung.',['Werkstoff','Konstruktion','Fertigung']),
  card('1202','Schweißgrundlagen','12','Welche drei Eigenschaften verbinden die Ecken des schweißtechnischen Dreiecks?','Schweißeignung, Schweißsicherheit und Schweißmöglichkeit.',['Schweißeignung','Schweißsicherheit','Schweißmöglichkeit']),
  card('1301','Schweißgrundlagen','13','Was bedeutet Schweißeignung?','Schweißeignung ist die werkstoffbezogene Eignung eines Werkstoffs, durch ein Schweißverfahren eine den Anforderungen entsprechende Verbindung zu bilden.',['Werkstoff','Eignung']),
  card('1302','Schweißgrundlagen','13','Wie unterscheidet sich Schweißbarkeit von Schweißeignung?','Schweißbarkeit beschreibt das Gesamtsystem aus Werkstoff, Konstruktion und Fertigung; Schweißeignung ist nur die werkstoffbezogene Komponente.',['Gesamtsystem','Werkstoff','Konstruktion','Fertigung']),
  card('1401','Schweißmetallurgie','14','Wie wird im Schaeffler-Diagramm das Mischgefüge aus zwei Grundwerkstoffen und einem Zusatzwerkstoff bestimmt?','Chrom- und Nickeläquivalente aller drei Werkstoffe eintragen, das Mischungsverhältnis über Verbindungslinien beziehungsweise den Schwerpunkt abbilden und das Endgefüge am resultierenden Punkt ablesen.',['Chromäquivalent','Nickeläquivalent','Mischungsverhältnis','Endgefüge'],3),
  card('1402','Schweißmetallurgie','14','Wozu dient das Schaeffler-Diagramm?','Zur Abschätzung des Gefüges hochlegierter Schweißgüter und Mischverbindungen aus Chrom- und Nickeläquivalent.',['Gefüge','Chromäquivalent','Nickeläquivalent']),
  card('1501','Lichtbogenschweißen','15','Welche grundlegenden Lichtbogenarten werden beim Metall-Schutzgasschweißen unterschieden?','Kurzlichtbogen, Übergangslichtbogen, Sprühlichtbogen und Impulslichtbogen.',['Kurzlichtbogen','Übergangslichtbogen','Sprühlichtbogen','Impulslichtbogen']),
  card('1601','Lichtbogenschweißen','16','Welche Achsen hat die Stromquellenkennlinie beim Lichtbogenschweißen?','Schweißstrom I auf der horizontalen und Lichtbogenspannung U auf der vertikalen Achse.',['Schweißstrom','Spannung']),
  card('1602','Lichtbogenschweißen','16','Welche Kennlinienform ist für Lichtbogenhandschweißen typisch?','Eine fallende beziehungsweise steile Stromquellenkennlinie, damit Stromänderungen bei Längenänderung des Lichtbogens begrenzt bleiben.',['fallende Kennlinie','Lichtbogenlänge']),
  card('1801','Lichtbogenschweißen','18','Wofür stehen MIG und MAG?','MIG bedeutet Metall-Inertgasschweißen, MAG Metall-Aktivgasschweißen.',['Metall-Inertgas','Metall-Aktivgas']),
  card('1802','Lichtbogenschweißen','18','Welche Schutzgase werden beim MIG-Schweißen eingesetzt?','Inerte Gase, vor allem Argon und Helium beziehungsweise deren Gemische.',['Argon','Helium','inert']),
  card('1803','Lichtbogenschweißen','18','Welche Schutzgase werden beim MAG-Schweißen eingesetzt?','Aktive Gase oder Mischgase, insbesondere CO₂ sowie Argon-Gemische mit CO₂ und/oder O₂.',['CO2','Argon','aktiv']),
  card('1901','Schweißmetallurgie','19','Welche Bereiche werden an einer Schweißverbindung unterschieden?','Schweißgut beziehungsweise Schmelzzone, Wärmeeinflusszone und unbeeinflusster Grundwerkstoff.',['Schweißgut','Wärmeeinflusszone','Grundwerkstoff']),
  card('1902','Schweißmetallurgie','19','Welche typischen Teilzonen können in der Wärmeeinflusszone eines Stahls auftreten?','Grobkornzone, Feinkornzone, interkritische beziehungsweise teilumgewandelte Zone und Anlass- beziehungsweise Rekristallisationsbereich.',['Grobkornzone','Feinkornzone','teilumgewandelt']),
  card('2101','Qualitätssicherung','21','Welche Gefügezone wird für mechanisch-technologische Prüfungen einer Schweißverbindung besonders betrachtet?','Die Wärmeeinflusszone, weil dort durch den thermischen Zyklus kritische Gefüge- und Härteänderungen auftreten können.',['Wärmeeinflusszone','Härte']),
  card('2201','Schweißmetallurgie','22','Was bedeutet die t8/5-Zeit?','Die Abkühlzeit eines Schweißguts beziehungsweise der Wärmeeinflusszone von 800 °C auf 500 °C.',['800','500','Abkühlzeit']),
  card('2202','Schweißmetallurgie','22','Wie beeinflusst eine kurze t8/5-Zeit die Martensitbildung?','Eine kurze t8/5-Zeit bedeutet schnelle Abkühlung und begünstigt Martensit, hohe Härte und Kaltrissgefahr.',['schnelle Abkühlung','Martensit','Härte','Kaltriss']),
  card('2203','Schweißmetallurgie','22','Wie beeinflusst eine lange t8/5-Zeit die Gefügebildung?','Langsame Abkühlung vermindert die Martensitbildung und begünstigt weichere Gefüge wie Ferrit und Perlit, kann aber bei sehr langer Wärmeeinwirkung Kornwachstum fördern.',['langsame Abkühlung','Ferrit','Perlit']),
  card('2301','Schweißmetallurgie','23a','Welche Gefüge entstehen bei zunehmender Abkühlgeschwindigkeit im Stahl typischerweise?','Mit zunehmender Abkühlgeschwindigkeit verschiebt sich die Bildung von Ferrit/Perlit über Bainit zu Martensit.',['Ferrit','Perlit','Bainit','Martensit']),
  card('2302','Schweißmetallurgie','23a','Wie verändert sich die Härte mit zunehmender Abkühlgeschwindigkeit?','Sie nimmt im Allgemeinen zu; Martensit weist die höchste Härte auf.',['Härte','Martensit']),
  card('2303','Schweißmetallurgie','23b','Bei welcher Abkühlgeschwindigkeit ist die Kaltrissgefahr höher?','Bei hoher Abkühlgeschwindigkeit, weil mehr hartes und sprödes Martensit entstehen kann.',['hohe Abkühlgeschwindigkeit','Martensit','Kaltriss']),
  card('2401','Schweißmetallurgie','24','Wie beeinflusst ein steigender Kohlenstoffgehalt Festigkeit, Härte und Dehnung von Stahl?','Festigkeit und Härte steigen, die Dehnung und damit die Verformbarkeit nehmen ab.',['Festigkeit steigt','Härte steigt','Dehnung sinkt']),
  card('2501','Schweißmetallurgie','25','Bis zu welchem Kohlenstoffgehalt gelten unlegierte Stähle im Allgemeinen als gut schweißgeeignet?','Als Richtwert bis etwa 0,22 Masse-% Kohlenstoff; die tatsächliche Schweißeignung hängt zusätzlich von Bauteildicke, Legierung und Prozess ab.',['0,22','Kohlenstoff']),
  card('2601','Schweißmetallurgie','26','Durch welchen Kennwert wird der gemeinsame Einfluss von Kohlenstoff und Legierungselementen auf die Schweißeignung beschrieben?','Durch das Kohlenstoffäquivalent, zum Beispiel CE beziehungsweise CEV.',['Kohlenstoffäquivalent','CEV']),
  card('2701','Schweißmetallurgie','27','Warum erhöht ein hoher Kohlenstoffgehalt die Kaltrissgefahr?','Er steigert die Härtbarkeit; bei schneller Abkühlung entsteht mehr harter, spröder Martensit, der zusammen mit Wasserstoff und Zugspannungen Kaltrisse begünstigt.',['Härtbarkeit','Martensit','Wasserstoff','Zugspannungen']),
  card('2801','Pressschweißen','28','Wie wird Pressschweißen im Gegensatz zum Schmelzschweißen realisiert?','Die Verbindung entsteht unter Anwendung von Kraft beziehungsweise Druck, mit oder ohne zusätzliche Erwärmung; die Fügeflächen müssen nicht vollständig aufgeschmolzen werden.',['Kraft','Druck','nicht vollständig aufgeschmolzen']),
  card('3001','Widerstandsschweißen','30','Welche zwei besonderen Schwierigkeiten bestehen beim Widerstandspunktschweißen von Aluminium?','Die stabile Oxidschicht besitzt hohen elektrischen Widerstand, während das Aluminium selbst sehr gut elektrisch und thermisch leitet; dadurch sind hohe Ströme, saubere Oberflächen und eine enge Prozessführung nötig.',['Oxidschicht','Wärmeleitfähigkeit','elektrische Leitfähigkeit','hohe Ströme'],3),
  card('3101','Strahlschweißen','31','Welcher Effekt wird beim Elektronenstrahl-Tiefschweißen genutzt?','Der Tiefschweißeffekt beziehungsweise Keyhole-Effekt: Verdampftes Material bildet einen Dampfkanal, in den der Strahl tief eindringen kann.',['Tiefschweißeffekt','Dampfkanal','Keyhole']),
  card('3102','Strahlschweißen','31','Welche Nahteigenschaft ergibt sich aus dem Tiefschweißeffekt beim Elektronenstrahlschweißen?','Sehr tiefe und gleichzeitig schmale Nähte mit großem Verhältnis von Nahttiefe zu Nahtbreite.',['tiefe','schmale Nähte','Aspektverhältnis']),
  card('3201','Strahlschweißen','32','Warum wird Laserschweißen in der Fertigung häufig gegenüber Elektronenstrahlschweißen bevorzugt?','Laserschweißen lässt sich leichter in automatisierte Fertigungslinien integrieren und benötigt keine Vakuumkammer; dadurch sind Handhabung und Taktbetrieb einfacher.',['Automatisierung','keine Vakuumkammer','Fertigungslinie']),
  card('3301','Strahlschweißen','33','Welche Wellenlänge hat ein CO₂-Laser?','Etwa 10,6 µm.',['10,6'],1,'numeric'),
  card('3401','Strahlschweißen','34','Welches Problem tritt beim Schweißen von Kupfer mit einem CO₂-Laser auf?','Kupfer absorbiert die langwellige CO₂-Laserstrahlung nur schlecht und reflektiert einen großen Anteil; die Energieeinkopplung ist daher ungünstig.',['geringe Absorption','Reflexion','10,6']),
  card('3501','Kleben','35','Was ist Klebstoff?','Der vor dem Fügen eingesetzte nichtmetallische Stoff, der die Fügeteile durch Adhäsion und Kohäsion verbindet.',['nichtmetallisch','Adhäsion','Kohäsion']),
  card('3502','Kleben','35','Was ist Kleber?','Kleber bezeichnet den abgebundenen beziehungsweise ausgehärteten Klebstoff in der Klebschicht.',['ausgehärtet','Klebschicht']),
  card('3701','Kleben','37','Welche Gleichgewichtsbeziehung gilt am Benetzungsrand nach Young?','Die Oberflächenspannungen stehen im Gleichgewicht: γ_SV = γ_SL + γ_LV · cos θ.',['γ_SV','γ_SL','γ_LV','cos'],3),
  card('3801','Kleben','38','Welche drei chemischen Reaktionsarten von Klebstoffen werden unterschieden?','Polymerisation, Polyaddition und Polykondensation.',['Polymerisation','Polyaddition','Polykondensation']),
  card('3802','Kleben','38','Nenne je ein typisches Beispiel für Polymerisations-, Polyadditions- und Polykondensationsklebstoffe.','Polymerisation: Acrylat- oder Cyanacrylatklebstoff; Polyaddition: Epoxidharz oder Polyurethan; Polykondensation: Phenolharz oder Silicon.',['Acrylat','Epoxidharz','Phenolharz']),
  card('3901','Kleben','39','Nenne drei Vorteile des Klebens.','Keine oder geringe Wärmeeinbringung, Verbindung unterschiedlicher Werkstoffe und flächige Kraftübertragung mit geringer Kerbwirkung.',['geringe Wärmeeinbringung','unterschiedliche Werkstoffe','flächige Kraftübertragung'],3),
  card('3902','Kleben','39','Nenne drei Nachteile des Klebens.','Empfindlichkeit gegen Temperatur sowie Schäl-, Biege- und Schlagbeanspruchung, hohe Anforderungen an Oberflächenvorbereitung und Aushärte- beziehungsweise Fixierzeit.',['Temperatur','Schälbeanspruchung','Oberflächenvorbereitung'],3),
  card('4101','Kleben','41','Aus welchen zwei Spannungsanteilen setzt sich der Beanspruchungsverlauf einer überlappten Klebverbindung zusammen?','Aus Schubspannungen in der Klebschicht und Schäl- beziehungsweise Normalspannungen, die besonders an den Überlappungsenden hoch sind.',['Schubspannung','Schälspannung','Überlappungsenden']),
  card('4201','Löten','42','Wie unterscheiden sich Löten und Schweißen hinsichtlich des Grundwerkstoffs?','Beide erzeugen Stoffschluss. Beim Schweißen wird der Grundwerkstoff in der Fügezone aufgeschmolzen oder plastifiziert; beim Löten schmilzt nur das Lot, der Grundwerkstoff wird benetzt, aber nicht geschmolzen.',['Stoffschluss','Lot','Grundwerkstoff nicht geschmolzen']),
  card('4301','Löten','43','Welches Problem besteht beim Löten von Aluminium?','Die dichte, hochschmelzende Aluminiumoxidschicht verhindert die Benetzung durch das Lot.',['Aluminiumoxid','Benetzung','Oxidschicht']),
  card('4302','Löten','43','Warum ist die Oxidschicht beim Aluminiumlöten besonders problematisch?','Aluminium oxidiert sehr schnell; die Oxidschicht ist chemisch stabil und schmilzt bei deutlich höherer Temperatur als Aluminium.',['schnelle Oxidation','stabil','höhere Schmelztemperatur']),
  card('4401','Löten','44','Wie kann die Oxidschicht beim Aluminiumlöten entfernt oder aufgebrochen werden?','Durch geeignete Flussmittel, mechanisches Aufbrechen beziehungsweise Reinigen oder Schutzgas- beziehungsweise Vakuumverfahren.',['Flussmittel','mechanisch','Schutzgas']),
  card('4402','Löten','44','Welches Folgeproblem kann durch Flussmittel entstehen?','Flussmittelreste können korrosiv wirken und müssen nach dem Löten sorgfältig entfernt werden.',['Flussmittelreste','Korrosion','entfernen']),
  card('4501','Löten','45','Wo wird Lot bei einer kapillaren Lötverbindung grundsätzlich zugeführt?','Am Eingang des gleichmäßigen, engen Lötspalts auf der der Wärmequelle gegenüberliegenden beziehungsweise günstig erwärmten Seite, sodass das geschmolzene Lot durch Kapillarwirkung in den Spalt gezogen wird.',['Lötspalt','Kapillarwirkung','Lotzuführung'],3)
];
