import './style.css';
import { createSnapshot, loadState, replaceState, saveState, type PersistedState } from './db';
import { applyReview } from './review-engine';
import { legacyQuestionVariantId, type FsrsShadowState, type ReviewEvent } from './model';

type Outcome='correct'|'partial'|'incorrect';
type Status='draft'|'reviewed'|'released'|'needs_review';
type QuestionType='free_text'|'numeric'|'drawing'|'image_labels';
type Card={id:string;version:number;changedAt:string;changeReason:string;status:Status;topicId:string;examQuestion:string;prompt:string;points:number;questionType:QuestionType;answer:{modelAnswer:string;requiredTerms?:string[];value?:number;tolerance?:{type:'absolute'|'relative';value:number};criteria?:string[]};source:string};
type Progress={stage:number;dueAt:string;correct:number;partial:number;incorrect:number;skipped:number;marked:boolean;cardVersion:number};
type History={cardId:string;outcome:Outcome;at:string};
type ExamAttempt={id:string;at:string;points:number;maxPoints:number;percentage:number;items:number};
type State=PersistedState&{progress:Record<string,Progress>;history:History[];reviewEvents:ReviewEvent[];fsrsShadow:Record<string,FsrsShadowState>;review:Record<string,string>;activeCatalog?:{catalogId:string;version:string;cards:Card[]};sessions:Record<string,unknown>;examAttempts:ExamAttempt[]};

const SOURCE='Fuegetechnikskript_SoSe2026.pdf / Gedächtnisprotokoll Fügetechnik SS24';
const nowIso=()=>new Date().toISOString();
const mk=(id:string,topicId:string,examQuestion:string,prompt:string,modelAnswer:string,requiredTerms:string[],points=2):Card=>({id:'ft'+id,version:1,changedAt:'2026-07-24T00:00:00.000Z',changeReason:'Initialer MVP-Katalog',status:'released',topicId,examQuestion,prompt,points,questionType:'free_text',answer:{modelAnswer,requiredTerms},source:SOURCE});
const builtin:Card[]=[
mk('01a1','Grundlagen','1a','Art des Zusammenhalts beim Elektronenstrahlschweißen?','Stoffschluss.',['Stoffschluss']),
mk('01a2','Grundlagen','1a','Fügegruppe des Elektronenstrahlschweißens?','Fügen durch Schweißen.',['Schweißen']),
mk('01a3','Grundlagen','1a','Lösbarkeit einer Elektronenstrahlschweißverbindung?','Unlösbar; Trennung nur zerstörend.',['unlösbar']),
mk('01b1','Grundlagen','1b','Art des Zusammenhalts beim Löten?','Stoffschluss.',['Stoffschluss']),
mk('01b2','Grundlagen','1b','Fügegruppe des Lötens?','Fügen durch Löten.',['Löten']),
mk('01b3','Grundlagen','1b','Lösbarkeit einer Lötverbindung?','Unlösbar.',['unlösbar']),
mk('01c1','Umformen','1c','Art des Zusammenhalts beim Durchsetzfügen?','Formschluss.',['Formschluss']),
mk('01c2','Umformen','1c','Fügegruppe des Durchsetzfügens?','Fügen durch Umformen.',['Umformen']),
mk('01c3','Umformen','1c','Lösbarkeit einer Durchsetzfügeverbindung?','Nur mit Veränderung, Schädigung oder Zerstörung lösbar.',['Schädigung','Zerstörung']),
mk('01d1','Schrauben','1d','Welche Wirkung sichert eine Schraube axial?','Formschluss des Gewindes.',['Formschluss','Gewinde']),
mk('01d2','Schrauben','1d','Welche Wirkung überträgt Querkräfte zwischen geklemmten Teilen?','Kraftschluss beziehungsweise Reibschluss.',['Kraftschluss','Reibschluss']),
mk('01d3','Schrauben','1d','Ist eine Schraubenverbindung lösbar?','Ja, in der Regel zerstörungsfrei lösbar.',['lösbar']),
mk('0201','Schrauben','2','Welche Kennwerte ergeben sich aus der Schrauben-Festigkeitsklasse?','Nennzugfestigkeit Rm und Streckgrenze beziehungsweise Rp0,2.',['Nennzugfestigkeit','Streckgrenze']),
mk('0202','Schrauben','2','Formel für Rm aus x.y?','Rm = 100 · x N/mm².',['100','x']),
mk('0203','Schrauben','2','Formel für Re aus x.y?','Re = 10 · x · y N/mm².',['10','x','y']),
mk('0301','Schrauben','3','Kraft je Schraube 8.9 bei 40 mm² und Ansatz Re?','720 N/mm² · 40 mm² = 28,8 kN.',['720','40','28,8'],3),
mk('0303','Schrauben','3','Warum 13,89 Schrauben aufrunden?','Nur ganze Schrauben sind möglich; Abrunden unterschreitet die nötige Tragfähigkeit.',['aufrunden','Tragfähigkeit']),
mk('0401','Schrauben','4','Drei Bestandteile von FMmin?','FKerf, FZ und FPA.',['FKerf','FZ','FPA']),
mk('0402','Schrauben','4','Formel für FMmin?','FMmin = FKerf + FZ + FPA.',['FMmin','FKerf','FZ','FPA']),
mk('0403','Schrauben','4','Aufgabe von FKerf?','Zusammenpressen, Reibschluss und gegebenenfalls Dichtpressen unter Betriebskräften.',['Zusammenpressen','Reibschluss','Dichtpressen']),
mk('0404','Schrauben','4','Wodurch entsteht FZ?','Setzen, Relaxation und Temperaturwechsel.',['Setzen','Relaxation','Temperaturwechsel']),
mk('0405','Schrauben','4','Was beschreibt FPA?','Entlastung der verspannten Bauteile durch die axiale Betriebskraft.',['Entlastung','Betriebskraft']),
mk('0502','Schrauben','5','Welche elastischen Systeme zeigt das Verspannungsschaubild?','Schraube als Zugfeder und Bauteile als Druckfeder.',['Zugfeder','Druckfeder']),
mk('0503','Schrauben','5','Warum unterscheiden sich Schraubenlängung und Plattenverkürzung?','Wegen unterschiedlicher Federsteifigkeiten.',['Federsteifigkeiten']),
mk('0701','Umformen','7','Vorteil des Umformfügens bezüglich Zusatzwerkstoffen?','Verbindungen ohne Zusatzwerkstoff bei geringem Materialeinsatz.',['ohne Zusatzwerkstoff','Materialeinsatz']),
mk('0702','Umformen','7','Vorteil des Umformfügens bezüglich Wärme?','Keine thermische Beeinflussung wie beim Schweißen und Löten.',['keine thermische Beeinflussung']),
mk('0703','Umformen','7','Vorteil der Kaltverfestigung?','Sie kann dünnere Wanddicken ermöglichen.',['Kaltverfestigung','dünnere Wanddicken']),
mk('0704','Umformen','7','Weitere Wirkung von Umformverbindungen?','Sie wirken häufig zusätzlich versteifend.',['versteifend']),
mk('0705','Umformen','7','Welche Festigkeit kann erreicht werden?','Bis hin zur Streckgrenze des Werkstoffs.',['Streckgrenze']),
mk('0706','Umformen','7','Nenne drei Vorteile des Fügens durch Umformen.','Geringer Materialeinsatz ohne Zusatzwerkstoff; keine thermische Beeinflussung; Kaltverfestigung beziehungsweise Versteifung.',['Materialeinsatz','thermische Beeinflussung','Kaltverfestigung'],3),
mk('0901','Umformen','9a','Welche Herausforderung besteht beim Halbhohlstanznieten von CFK?','CFK ist spröde; beim Durchdringen können Delamination und Faserschädigung auftreten.',['spröde','Delamination','Faserschädigung']),
mk('0902','Umformen','9a','Welche weitere Herausforderung betrifft den Hinterschnitt in CFK?','Die geringe plastische Verformbarkeit erschwert die Ausbildung eines tragfähigen Hinterschnitts.',['plastische Verformbarkeit','Hinterschnitt']),
mk('0903','Umformen','9b','Welches alternative Verfahren kommt für zwei CFK-Bleche in Betracht?','Kleben, weil keine lokale Durchdringung und starke plastische Umformung erforderlich ist.',['Kleben']),
mk('1002','Umformen','10','Was zeigt ein Verlassen des Toleranzbands im Kraft-Weg-Verlauf?','Eine Prozess- oder Qualitätsabweichung der Clinchverbindung.',['Prozessabweichung','Qualitätsabweichung']),
mk('1101','Umformen','11','Warum ist eine allgemeine rechnerische Festigkeitsabschätzung beim Durchsetzfügen schwierig?','Viele Werkstoff-, Geometrie-, Oberflächen-, Werkzeug- und Prozessparameter beeinflussen die Verbindung.',['Werkstoff','Geometrie','Oberfläche','Werkzeug','Prozess']),
mk('1102','Umformen','11','Welche Maßnahme kann die Dauerfestigkeit beim Durchsetzfügen erhöhen?','Klebstoff im Fügespalt.',['Klebstoff','Fügespalt']),
mk('1103','Umformen','11','Welcher zusätzliche Nutzen kann durch Klebstoff im Fügespalt entstehen?','Eine dichte Verbindung.',['dichte Verbindung']),
mk('1104','Umformen','11','Welches Ersatzverfahren ist für hochdynamische Bereiche naheliegend?','Eine kombinierte oder alternative Verbindung mit höherer Dauerfestigkeit, insbesondere Kleben beziehungsweise Clinchkleben; die konkrete Vorlesungsaussage ist zu verifizieren.',['Kleben','Dauerfestigkeit'])
];
for(const [id,q,v] of [['0259rm','Rm für 5.9?',500],['0259re','Re für 5.9?',450],['0289rm','Rm für 8.9?',800],['0289re','Re für 8.9?',720],['02129rm','Rm für 12.9?',1200],['02129re','Re für 12.9?',1080],['0302','Mindestanzahl Schrauben 8.9 mit 40 mm² für 400 kN?',14]] as [string,string,number][])builtin.push({id:'ft'+id,version:1,changedAt:'2026-07-24T00:00:00.000Z',changeReason:'Initialer MVP-Katalog',status:'released',topicId:'Schrauben',examQuestion:id==='0302'?'3':'2',prompt:q,points:id==='0302'?3:1,questionType:'numeric',answer:{modelAnswer:String(v),value:v,tolerance:{type:'absolute',value:0}},source:SOURCE});
builtin.push({id:'ft0501',version:1,changedAt:'2026-07-24T00:00:00.000Z',changeReason:'Initialer MVP-Katalog',status:'released',topicId:'Schrauben',examQuestion:'5',prompt:'Zeichne das Verspannungsschaubild.',points:4,questionType:'drawing',answer:{modelAnswer:'Schraubenkennlinie, gespiegelte Bauteilkennlinie, Kraft- und Verformungsachse sowie Montagevorspannkraft eintragen.',criteria:['Schraubenkennlinie','gespiegelte Bauteilkennlinie','Kraftachse','Verformungsachse','Montagevorspannkraft']},source:SOURCE});
builtin.push({id:'ft1001',version:1,changedAt:'2026-07-24T00:00:00.000Z',changeReason:'Initialer MVP-Katalog',status:'released',topicId:'Umformen',examQuestion:'10',prompt:'Zeichne den Kraft-Weg-Verlauf einer Clinchverbindung mit Toleranzband und einer qualitativ schlechten Kurve.',points:5,questionType:'drawing',answer:{modelAnswer:'Referenzkurve mit unterer und oberer Toleranzgrenze; schlechte Kurve verlässt das Toleranzband.',criteria:['Kraftachse','Wegachse','Referenzkurve','oberes Toleranzband','unteres Toleranzband','Fehlerkurve außerhalb des Bands']},source:SOURCE});
for(const [id,q] of [['0601','Welches Verfahren ist auf dem fehlenden Prüfungsbild zu sehen?'],['0602','Nenne je einen Vor- und Nachteil des auf dem fehlenden Prüfungsbild gezeigten Verfahrens.'],['0801','Welches Verfahren ist auf dem zweiten fehlenden Prüfungsbild zu sehen?'],['0802','Beschrifte das zweite fehlende Prüfungsbild.']] as [string,string][])builtin.push({id:'ft'+id,version:1,changedAt:'2026-07-25T00:00:00.000Z',changeReason:'Prüfungsbild liegt nicht vor',status:'needs_review',topicId:'Umformen',examQuestion:id.slice(0,2),prompt:q,points:2,questionType:'free_text',answer:{modelAnswer:'Nicht aus den bereitgestellten Textquellen ableitbar.',requiredTerms:[]},source:SOURCE});

let state:State={schemaVersion:3,progress:{},history:[],reviewEvents:[],fsrsShadow:{},review:{},sessions:{},examAttempts:[],migrationLog:[]};
let cards:Card[]=builtin,view='dashboard',queue:Card[]=[],retry:Card[]=[],current:Card|undefined,revealed=false,answerText='',topic='all',examMode=false,examPoints=0,examMax=0,questionStartedAt=Date.now();
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!));
const norm=(s:string)=>s.toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const blank=(c:Card):Progress=>({stage:1,dueAt:new Date(0).toISOString(),correct:0,partial:0,incorrect:0,skipped:0,marked:false,cardVersion:c.version});
const progressId=(c:Card)=>c.id.replace(/#exam\d+$/,'');
const progress=(c:Card)=>state.progress[progressId(c)]??blank(c);const due=(p:Progress)=>new Date(p.dueAt).getTime()<=Date.now();
const persist=async()=>saveState(state);
function activeCards(){const imported=state.activeCatalog?.cards;cards=Array.isArray(imported)&&imported.length?imported:builtin;return cards.filter(c=>(state.review[c.id]??c.status)==='released')}
function validateCard(x:any):x is Card{return x&&typeof x.id==='string'&&typeof x.prompt==='string'&&typeof x.topicId==='string'&&['draft','reviewed','released','needs_review'].includes(x.status)&&['free_text','numeric','drawing','image_labels'].includes(x.questionType)&&x.answer&&typeof x.answer.modelAnswer==='string'}
function validateCatalog(x:any){const errors:string[]=[];if(!x||typeof x!=='object')errors.push('Kein JSON-Objekt');if(typeof x.catalogId!=='string')errors.push('catalogId fehlt');if(typeof x.version!=='string')errors.push('version fehlt');if(!Array.isArray(x.cards))errors.push('cards fehlt');const ids=new Set<string>();for(const [i,c] of (x.cards??[]).entries()){if(!validateCard(c))errors.push(`Karte ${i+1} ist ungültig`);else if(ids.has(c.id))errors.push(`Doppelte ID ${c.id}`);else ids.add(c.id)}return errors}
function grade(o:Outcome){if(!current)return;const id=progressId(current),answeredAt=new Date();applyReview(state,{knowledgeItemId:id,questionVariantId:legacyQuestionVariantId(id),cardVersion:current.version},o,examMode?'exam':'learning',answeredAt,Math.max(0,answeredAt.getTime()-questionStartedAt),{fsrsShadowEnabled:true});if(examMode){examMax+=current.points;examPoints+=o==='correct'?current.points:o==='partial'?current.points/2:0}else if(o!=='correct')retry.push(current);void persist();next()}
function start(mode:string){const all=activeCards().filter(c=>topic==='all'||c.topicId===topic);queue=mode==='new'?all.filter(c=>!state.progress[c.id]):mode==='errors'?all.filter(c=>progress(c).incorrect>0):mode==='all'?[...all]:all.filter(c=>due(progress(c)));queue.sort((a,b)=>progress(a).stage-progress(b).stage||new Date(progress(a).dueAt).getTime()-new Date(progress(b).dueAt).getTime()||Math.random()-.5);retry=[];examMode=false;view='session';next()}
function startExam(){const source=activeCards();if(!source.length)return alert('Keine freigegebenen Karten.');const selected:Card[]=[];for(let i=0;i<57;i++)selected.push({...source[i%source.length],id:`${source[i%source.length].id}#exam${i+1}`});let remaining=202;selected.forEach((c,i)=>{const slots=selected.length-i;c.points=Math.max(1,Math.round(remaining/slots));remaining-=c.points});selected[selected.length-1].points+=remaining;queue=selected.sort(()=>Math.random()-.5);retry=[];examMode=true;examPoints=0;examMax=0;view='session';next()}
function next(){revealed=false;answerText='';current=queue.shift()??retry.shift();if(current)questionStartedAt=Date.now();if(!current&&examMode){const attempt={id:crypto.randomUUID(),at:nowIso(),points:examPoints,maxPoints:examMax,percentage:examMax?Math.round(examPoints/examMax*100):0,items:57};state.examAttempts.push(attempt);void persist();examMode=false;view='exam';alert(`Prüfung beendet: ${attempt.points} / ${attempt.maxPoints} Punkte (${attempt.percentage} %)`)}render()}
function nav(){return `<div class="nav">${[['dashboard','Übersicht'],['learn','Lernen'],['exam','Prüfung'],['stats','Statistik'],['review','Review'],['data','Daten']].map(x=>`<button class="${view===x[0]?'active':''}" data-view="${x[0]}">${x[1]}</button>`).join('')}</div>`}
function frame(body:string){return `<main class="shell"><header class="top"><div><h1>Exam Trainer Framework</h1><div class="muted">Fügetechnik MVP · ${activeCards().length} freigegeben · IndexedDB</div></div>${nav()}</header>${body}</main>`}
function metrics(){const all=activeCards(),ps=all.map(progress),h=state.history,ok=h.filter(x=>x.outcome==='correct').length;return{all,ps,due:ps.filter(due).length,newc:all.filter(c=>!state.progress[c.id]).length,rate:h.length?Math.round(ok/h.length*100):0}}
function dashboard(){const m=metrics();return frame(`<div class="notice">Offline-PWA ohne Telemetrie. Lernstand und importierter Katalog bleiben in IndexedDB; regelmäßig Backup exportieren.</div><div class="grid" style="margin-top:1rem"><section class="card"><div class="muted">Fällig</div><div class="metric">${m.due}</div><button class="btn primary" data-start="due">Lernen</button></section><section class="card"><div class="muted">Neu</div><div class="metric">${m.newc}</div><button class="btn" data-start="new">Neue Karten</button></section><section class="card"><div class="muted">Richtig</div><div class="metric">${m.rate}%</div></section><section class="card"><div class="muted">Karten</div><div class="metric">${m.all.length}</div></section></div><section class="card" style="margin-top:1rem"><h2>Stufen</h2>${[1,2,3,4,5].map(s=>`<div>Stufe ${s}: ${m.ps.filter(p=>p.stage===s).length}<div class="progressbar"><div style="width:${m.all.length?m.ps.filter(p=>p.stage===s).length/m.all.length*100:0}%"></div></div></div>`).join('')}</section>`)}
function setup(){const topics=[...new Set(activeCards().map(c=>c.topicId))];return frame(`<section class="card"><h2>Lernsitzung</h2><div class="toolbar"><select id="mode"><option value="due">Fällige</option><option value="new">Neue</option><option value="errors">Fehlerkarten</option><option value="all">Alle</option></select><select id="topic"><option value="all">Alle Themen</option>${topics.map(t=>`<option>${esc(t)}</option>`).join('')}</select><button class="btn primary" data-custom>Starten</button></div></section>`)}
function advisory(c:Card,text:string){if(c.questionType==='numeric'&&c.answer.value!==undefined){const n=Number(text.replace(',','.')),tol=c.answer.tolerance??{type:'absolute' as const,value:0},ok=tol.type==='absolute'?Math.abs(n-c.answer.value)<=tol.value:Math.abs(n-c.answer.value)/Math.abs(c.answer.value)<=tol.value;return ok?'Zahlenwert innerhalb der Toleranz.':'Zahlenwert außerhalb der Toleranz.'}const req=c.answer.requiredTerms??[];const n=norm(text),missing=req.filter(t=>!n.includes(norm(t)));return missing.length?`Fehlende Pflichtbegriffe: ${missing.join(', ')}`:'Alle konfigurierten Pflichtbegriffe erkannt.'}
function session(){if(!current)return frame(`<section class="card"><h2>Sitzung beendet</h2><button class="btn primary" data-view="dashboard">Zur Übersicht</button></section>`);const p=progress(current);return frame(`<section class="card"><div class="muted">${examMode?'Prüfung':'Lernen'} · ${esc(current.topicId)} · Aufgabe ${esc(current.examQuestion)} · ${current.points} Punkte</div><h2>${esc(current.prompt)}</h2>${current.questionType==='drawing'?'<p>Fertige die Zeichnung auf Papier oder in einer geeigneten Zeichen-App an.</p>':`<textarea id="answer" rows="6" placeholder="Antwort eingeben">${esc(answerText)}</textarea>`}${!revealed?`<div class="actions"><button class="btn" data-skip>Überspringen</button><button class="btn" data-mark>${p.marked?'Markierung entfernen':'Markieren'}</button><button class="btn primary" data-reveal>Lösung zeigen</button></div>`:`<div class="solution"><h3>Musterlösung</h3><p>${esc(current.answer.modelAnswer)}</p>${current.answer.criteria?`<ul>${current.answer.criteria.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<p><strong>Bewertungshilfe:</strong> ${esc(advisory(current,answerText))}</p><p class="muted">Quelle: ${esc(current.source)}</p></div><div class="actions"><button class="btn bad" data-grade="incorrect">Falsch</button><button class="btn" data-grade="partial">Teilweise</button><button class="btn primary" data-grade="correct">Richtig</button></div>`}</section>`)}
function exam(){const a=state.examAttempts.at(-1);return frame(`<section class="card"><h2>Prüfungssimulation</h2><p>Die Simulation erzeugt exakt 57 Aufgaben und 202 Punkte. Solange der Vollkatalog weniger als 57 freigegebene Karten enthält, werden Karten als Varianten wiederverwendet.</p>${a?`<div class="notice">Letztes Ergebnis: ${a.points} / ${a.maxPoints} Punkte (${a.percentage} %)</div>`:''}<button class="btn primary" data-exam>Simulation starten</button></section>`)}
function stats(){const m=metrics();return frame(`<section class="card"><h2>Statistik</h2><table class="table"><tr><th>Karte</th><th>Stufe</th><th>R</th><th>T</th><th>F</th><th>Fällig</th></tr>${m.all.map(c=>{const p=progress(c);return `<tr><td>${esc(c.id)}</td><td>${p.stage}</td><td>${p.correct}</td><td>${p.partial}</td><td>${p.incorrect}</td><td>${due(p)?'ja':'nein'}</td></tr>`}).join('')}</table></section>`)}
function reviewView(){return frame(`<section class="card"><h2>Redaktioneller Review</h2><p>Statusänderungen werden lokal gespeichert und wirken sofort auf Lernen und Prüfung.</p><table class="table"><tr><th>ID</th><th>Frage</th><th>Status</th></tr>${cards.map(c=>`<tr><td>${esc(c.id)}</td><td>${esc(c.prompt)}</td><td><select data-status="${esc(c.id)}">${['draft','reviewed','released','needs_review'].map(s=>`<option ${s===(state.review[c.id]??c.status)?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</table></section>`)}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({format:'etf-learner-backup',schemaVersion:3,createdAt:nowIso(),appVersion:'0.4.0',state},null,2)],{type:'application/json'}));a.download=`etf-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function dataView(){return frame(`<section class="card"><h2>Daten</h2><div class="actions"><button class="btn primary" data-export>Backup exportieren</button><label class="btn">Backup importieren<input id="import" hidden type="file" accept="application/json"></label><label class="btn">Katalog importieren<input id="catalog" hidden type="file" accept="application/json"></label><button class="btn" data-reset-topic>Thema zurücksetzen</button><button class="btn bad" data-reset>Alles zurücksetzen</button></div><p class="muted">Aktiver Katalog: ${esc(state.activeCatalog?.catalogId??'integrierter Fügetechnik-Katalog')} ${esc(state.activeCatalog?.version??'')}</p><p class="muted">Migrationen: ${state.migrationLog?.length??0}</p></section>`)}
async function importBackup(file:File){const x=JSON.parse(await file.text());if(x.format!=='etf-learner-backup'||!x.state)throw Error('Ungültiges ETF-Backup');state=await replaceState(x.state,state,'backup-import') as State;render()}
async function importCatalog(file:File){const x=JSON.parse(await file.text()),errors=validateCatalog(x);if(errors.length)throw Error(errors.join('\n'));await createSnapshot(state,'catalog-import');state.activeCatalog={catalogId:x.catalogId,version:x.version,cards:x.cards};await persist();activeCards();alert(`${x.cards.length} Karten importiert.`);render()}
async function resetAll(){if(!confirm('Vor dem Reset wird ein Backup heruntergeladen und ein interner Snapshot erstellt. Fortfahren?'))return;download();await createSnapshot(state,'full-reset');state={schemaVersion:3,progress:{},history:[],reviewEvents:[],fsrsShadow:{},review:{},sessions:{},examAttempts:[],migrationLog:state.migrationLog??[],activeCatalog:state.activeCatalog};await persist();render()}
async function resetTopic(){const t=prompt('Thema exakt eingeben:');if(!t)return;const ids=cards.filter(c=>c.topicId===t).map(c=>c.id);if(!ids.length)return alert('Thema nicht gefunden.');if(!confirm(`${ids.length} Karten des Themas ${t} zurücksetzen?`))return;await createSnapshot(state,'topic-reset');for(const id of ids){delete state.progress[id];delete state.fsrsShadow[id]}await persist();render()}
function bind(){document.querySelectorAll('[data-view]').forEach(e=>e.addEventListener('click',()=>{view=(e as HTMLElement).dataset.view!;current=undefined;render()}));document.querySelectorAll('[data-start]').forEach(e=>e.addEventListener('click',()=>start((e as HTMLElement).dataset.start!)));document.querySelector('[data-custom]')?.addEventListener('click',()=>{topic=(document.querySelector('#topic') as HTMLSelectElement).value;start((document.querySelector('#mode') as HTMLSelectElement).value)});document.querySelector('[data-reveal]')?.addEventListener('click',()=>{answerText=(document.querySelector('#answer') as HTMLTextAreaElement|null)?.value??'';revealed=true;render()});document.querySelectorAll('[data-grade]').forEach(e=>e.addEventListener('click',()=>grade((e as HTMLElement).dataset.grade as Outcome)));document.querySelector('[data-skip]')?.addEventListener('click',()=>{if(!current)return;const p=progress(current);p.skipped++;state.progress[progressId(current)]=p;queue.push(current);void persist();next()});document.querySelector('[data-mark]')?.addEventListener('click',()=>{if(!current)return;const p=progress(current);p.marked=!p.marked;state.progress[progressId(current)]=p;void persist();render()});document.querySelector('[data-exam]')?.addEventListener('click',startExam);document.querySelector('[data-export]')?.addEventListener('click',download);document.querySelector('#import')?.addEventListener('change',async e=>{try{const f=(e.target as HTMLInputElement).files?.[0];if(f)await importBackup(f)}catch(err){alert(String(err))}});document.querySelector('#catalog')?.addEventListener('change',async e=>{try{const f=(e.target as HTMLInputElement).files?.[0];if(f)await importCatalog(f)}catch(err){alert(String(err))}});document.querySelector('[data-reset]')?.addEventListener('click',()=>void resetAll());document.querySelector('[data-reset-topic]')?.addEventListener('click',()=>void resetTopic());document.querySelectorAll('[data-status]').forEach(e=>e.addEventListener('change',async()=>{const s=e as HTMLSelectElement;state.review[s.dataset.status!]=s.value;await persist();render()}));}
function render(){const app=document.querySelector('#app')!;app.innerHTML=view==='dashboard'?dashboard():view==='learn'?setup():view==='session'?session():view==='exam'?exam():view==='stats'?stats():view==='review'?reviewView():dataView();bind()}
window.addEventListener('keydown',e=>{if((e.target as HTMLElement)?.matches('textarea,input,select'))return;if(view==='session'&&!revealed&&(e.key===' '||e.key==='Enter')){e.preventDefault();revealed=true;render()}else if(view==='session'&&revealed&&['1','2','3'].includes(e.key))grade(e.key==='1'?'incorrect':e.key==='2'?'partial':'correct');else if(view==='session'&&e.key.toLowerCase()==='s'&&current){queue.push(current);next()}});
async function init(){state=await loadState(state) as State;activeCards();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render()}
void init();