import './style.css';

type Outcome='correct'|'partial'|'incorrect';
type Card={id:string;status:'released'|'needs_review';topicId:string;examQuestion:string;prompt:string;points:number;questionType:'free_text'|'numeric'|'drawing';answer:{modelAnswer:string;requiredTerms?:string[];value?:number;criteria?:string[]};source:string};
type Progress={stage:number;dueAt:string;correct:number;partial:number;incorrect:number;marked:boolean};
type State={progress:Record<string,Progress>;history:{cardId:string;outcome:Outcome;at:string}[];review:Record<string,string>};

const I=[0,600000,86400000,259200000,604800000,1814400000];
const SOURCE='Fuegetechnikskript_SoSe2026.pdf / Gedächtnisprotokoll Fügetechnik SS24';
const raw:[string,string,string,string,string,string[]][]=[
['01a1','Grundlagen','1a','Art des Zusammenhalts beim Elektronenstrahlschweißen?','Stoffschluss.',['Stoffschluss']],
['01a2','Grundlagen','1a','Fügegruppe des Elektronenstrahlschweißens?','Fügen durch Schweißen.',['Schweißen']],
['01a3','Grundlagen','1a','Lösbarkeit einer Elektronenstrahlschweißverbindung?','Unlösbar; Trennung nur zerstörend.',['unlösbar']],
['01b1','Grundlagen','1b','Art des Zusammenhalts beim Löten?','Stoffschluss.',['Stoffschluss']],
['01b2','Grundlagen','1b','Fügegruppe des Lötens?','Fügen durch Löten.',['Löten']],
['01b3','Grundlagen','1b','Lösbarkeit einer Lötverbindung?','Als unlösbare Verbindung einzuordnen.',['unlösbar']],
['01c1','Umformen','1c','Art des Zusammenhalts beim Durchsetzfügen?','Formschluss.',['Formschluss']],
['01c2','Umformen','1c','Fügegruppe des Durchsetzfügens?','Fügen durch Umformen.',['Umformen']],
['01c3','Umformen','1c','Lösbarkeit einer Durchsetzfügeverbindung?','Unlösbar.',['unlösbar']],
['01d1','Schrauben','1d','Welche Wirkung sichert eine Schraube axial?','Formschluss des Gewindes.',['Formschluss','Gewinde']],
['01d2','Schrauben','1d','Welche Wirkung kann Querkräfte zwischen geklemmten Teilen übertragen?','Kraftschluss beziehungsweise Reibschluss.',['Kraftschluss','Reibschluss']],
['01d3','Schrauben','1d','Ist eine Schraubenverbindung lösbar?','Ja, in der Regel zerstörungsfrei lösbar.',['lösbar']],
['0201','Schrauben','2','Welche Kennwerte ergeben sich aus der Schrauben-Festigkeitsklasse?','Nennzugfestigkeit Rm und Streckgrenze beziehungsweise Rp0,2.',['Nennzugfestigkeit','Streckgrenze']],
['0202','Schrauben','2','Formel für Rm aus x.y?','Rm = 100 · x N/mm².',['100','x']],
['0203','Schrauben','2','Formel für Re aus x.y?','Re = 10 · x · y N/mm².',['10','x','y']],
['0301','Schrauben','3','Kraft je Schraube 8.9 bei 40 mm² und Ansatz Re?','720 N/mm² · 40 mm² = 28,8 kN.',['720','40','28,8']],
['0303','Schrauben','3','Warum 13,89 Schrauben aufrunden?','Nur ganze Schrauben sind möglich; Abrunden unterschreitet die nötige Tragfähigkeit.',['aufrunden','Tragfähigkeit']],
['0401','Schrauben','4','Drei Bestandteile von FMmin?','FKerf, FZ und FPA.',['FKerf','FZ','FPA']],
['0402','Schrauben','4','Formel für FMmin?','FMmin = FKerf + FZ + FPA.',['FMmin','FKerf','FZ','FPA']],
['0403','Schrauben','4','Aufgabe von FKerf?','Zusammenpressen, Reibschluss und gegebenenfalls Dichtpressen unter Betriebskräften.',['Zusammenpressen','Reibschluss','Dichtpressen']],
['0404','Schrauben','4','Wodurch entsteht FZ?','Setzen, Relaxation und Temperaturwechsel.',['Setzen','Relaxation','Temperaturwechsel']],
['0405','Schrauben','4','Was beschreibt FPA?','Entlastung der verspannten Bauteile durch die axiale Betriebskraft.',['Entlastung','Betriebskraft']],
['0502','Schrauben','5','Welche elastischen Systeme zeigt das Verspannungsschaubild?','Schraube als Zugfeder und Bauteile als Druckfeder.',['Zugfeder','Druckfeder']],
['0503','Schrauben','5','Warum unterscheiden sich Schraubenlängung und Plattenverkürzung?','Wegen unterschiedlicher Federsteifigkeiten.',['Federsteifigkeiten']],
['0701','Umformen','7','Vorteil des Umformfügens bezüglich Zusatzwerkstoffen?','Verbindungen ohne Zusatzwerkstoff bei geringem Materialeinsatz.',['ohne Zusatzwerkstoff','Materialeinsatz']],
['0702','Umformen','7','Vorteil des Umformfügens bezüglich Wärme?','Keine thermische Beeinflussung wie beim Schweißen und Löten.',['keine thermische Beeinflussung']],
['0703','Umformen','7','Vorteil der Kaltverfestigung?','Sie kann dünnere Wanddicken ermöglichen.',['Kaltverfestigung','dünnere Wanddicken']],
['0704','Umformen','7','Weitere Wirkung von Umformverbindungen?','Sie wirken häufig zusätzlich versteifend.',['versteifend']],
['0705','Umformen','7','Welche Festigkeit kann erreicht werden?','Bis hin zur Streckgrenze des Werkstoffs.',['Streckgrenze']],
['0706','Umformen','7','Nenne drei Vorteile des Fügens durch Umformen.','Geringer Materialeinsatz ohne Zusatzwerkstoff; keine thermische Beeinflussung; Kaltverfestigung beziehungsweise Versteifung.',['Materialeinsatz','thermische Beeinflussung','Kaltverfestigung']],
['1101','Umformen','11','Warum ist eine allgemeine rechnerische Festigkeitsabschätzung beim Durchsetzfügen schwierig?','Viele Werkstoff-, Geometrie-, Oberflächen-, Werkzeug- und Prozessparameter beeinflussen die Verbindung.',['viele Parameter']],
['1102','Umformen','11','Welche Maßnahme kann die Dauerfestigkeit beim Durchsetzfügen erhöhen?','Klebstoff im Fügespalt.',['Klebstoff','Fügespalt']],
['1103','Umformen','11','Welcher zusätzliche Nutzen kann durch Klebstoff im Fügespalt entstehen?','Eine dichte Verbindung.',['dichte Verbindung']]
];
const cards:Card[]=raw.map(x=>({id:'ft'+x[0],status:'released',topicId:x[1],examQuestion:x[2],prompt:x[3],points:2,questionType:'free_text',answer:{modelAnswer:x[4],requiredTerms:x[5]},source:SOURCE}));
for(const [id,q,v] of [['0259rm','Rm für 5.9?',500],['0259re','Re für 5.9?',450],['0289rm','Rm für 8.9?',800],['0289re','Re für 8.9?',720],['02129rm','Rm für 12.9?',1200],['02129re','Re für 12.9?',1080],['0302','Mindestanzahl Schrauben 8.9 mit 40 mm² für 400 kN?',14]] as [string,string,number][])cards.push({id:'ft'+id,status:'released',topicId:'Schrauben',examQuestion:id==='0302'?'3':'2',prompt:q,points:id==='0302'?3:1,questionType:'numeric',answer:{modelAnswer:String(v),value:v},source:SOURCE});
cards.push({id:'ft0501',status:'released',topicId:'Schrauben',examQuestion:'5',prompt:'Zeichne das Verspannungsschaubild.',points:4,questionType:'drawing',answer:{modelAnswer:'Schraubenkennlinie, gespiegelte Bauteilkennlinie, Kraft- und Verformungsachse sowie Montagevorspannkraft eintragen.',criteria:['Schraubenkennlinie','gespiegelte Bauteilkennlinie','Kraftachse','Verformungsachse','Montagevorspannkraft']},source:SOURCE});
const review=[['0601','6a','Welches Verfahren ist auf dem Prüfungsbild zu sehen?'],['0602','6b','Nenne je einen Vor- und Nachteil des gezeigten Verfahrens.'],['0801','8a','Welches Verfahren ist auf dem zweiten Prüfungsbild zu sehen?'],['0802','8b','Beschrifte das zweite Prüfungsbild.'],['0901','9a','Welche Herausforderung besteht beim Halbhohlstanznieten von CFK?'],['0902','9a','Welche weitere Herausforderung betrifft den Hinterschnitt in CFK?'],['0903','9b','Welches alternative Verfahren kommt für zwei CFK-Bleche in Betracht?'],['1001','10','Zeichne den Kraft-Weg-Verlauf einer Clinchverbindung mit Toleranzband.'],['1002','10','Was zeigt ein Verlassen des Toleranzbands?'],['1104','11','Welches Ersatzverfahren wurde für hochdynamische Bereiche genannt?']];
for(const x of review)cards.push({id:'ft'+x[0],status:'needs_review',topicId:'Umformen',examQuestion:x[1],prompt:x[2],points:2,questionType:'free_text',answer:{modelAnswer:'Vor Freigabe anhand des Skripts beziehungsweise fehlenden Prüfungsbildes verifizieren.',requiredTerms:['zu prüfen']},source:SOURCE});

const KEY='etf-state-v1';let state:State={progress:{},history:[],review:{}};try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
let view='dashboard',queue:Card[]=[],retry:Card[]=[],current:Card|undefined,revealed=false,answerText='',topic='all';
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!));
const norm=(s:string)=>s.toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const blank=():Progress=>({stage:1,dueAt:new Date(0).toISOString(),correct:0,partial:0,incorrect:0,marked:false});
const progress=(c:Card)=>state.progress[c.id]??blank();const due=(p:Progress)=>new Date(p.dueAt).getTime()<=Date.now();const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function grade(o:Outcome){if(!current)return;const p=progress(current);if(o==='correct'){p.stage=Math.min(5,p.stage+1);p.correct++}if(o==='partial')p.partial++;if(o==='incorrect'){p.stage=Math.max(1,p.stage-1);p.incorrect++}p.dueAt=new Date(Date.now()+(o==='partial'?I[p.stage]/2:I[p.stage])).toISOString();state.progress[current.id]=p;state.history.push({cardId:current.id,outcome:o,at:new Date().toISOString()});if(o!=='correct')retry.push(current);save();next()}
function start(mode:string){const all=cards.filter(c=>c.status==='released'&&(topic==='all'||c.topicId===topic));queue=mode==='new'?all.filter(c=>!state.progress[c.id]):mode==='errors'?all.filter(c=>progress(c).incorrect>0):mode==='all'?[...all]:all.filter(c=>due(progress(c)));queue.sort((a,b)=>progress(a).stage-progress(b).stage||new Date(progress(a).dueAt).getTime()-new Date(progress(b).dueAt).getTime()||Math.random()-.5);retry=[];view='session';next()}
function next(){revealed=false;answerText='';current=queue.shift()??retry.shift();render()}
function nav(){return `<div class="nav">${[['dashboard','Übersicht'],['learn','Lernen'],['exam','Prüfung'],['stats','Statistik'],['review','Review'],['data','Daten']].map(x=>`<button class="${view===x[0]?'active':''}" data-view="${x[0]}">${x[1]}</button>`).join('')}</div>`}
function frame(body:string){return `<main class="shell"><header class="top"><div><h1>Exam Trainer Framework</h1><div class="muted">Fügetechnik MVP · ${cards.filter(c=>c.status==='released').length} freigegeben</div></div>${nav()}</header>${body}</main>`}
function metrics(){const all=cards.filter(c=>c.status==='released'),ps=all.map(progress),h=state.history,ok=h.filter(x=>x.outcome==='correct').length;return{all,ps,due:ps.filter(due).length,newc:all.filter(c=>!state.progress[c.id]).length,rate:h.length?Math.round(ok/h.length*100):0}}
function dashboard(){const m=metrics();return frame(`<div class="notice">Offline-PWA ohne Telemetrie. Der Lernstand bleibt lokal; regelmäßig Backup exportieren.</div><div class="grid" style="margin-top:1rem"><section class="card"><div class="muted">Fällig</div><div class="metric">${m.due}</div><button class="btn primary" data-start="due">Lernen</button></section><section class="card"><div class="muted">Neu</div><div class="metric">${m.newc}</div><button class="btn" data-start="new">Neue Karten</button></section><section class="card"><div class="muted">Richtig</div><div class="metric">${m.rate}%</div></section><section class="card"><div class="muted">Karten</div><div class="metric">${m.all.length}</div></section></div><section class="card" style="margin-top:1rem"><h2>Stufen</h2>${[1,2,3,4,5].map(s=>`<div>Stufe ${s}: ${m.ps.filter(p=>p.stage===s).length}<div class="progressbar"><div style="width:${m.all.length?m.ps.filter(p=>p.stage===s).length/m.all.length*100:0}%"></div></div></div>`).join('')}</section>`)}
function setup(){const topics=[...new Set(cards.filter(c=>c.status==='released').map(c=>c.topicId))];return frame(`<section class="card"><h2>Lernsitzung</h2><div class="toolbar"><select id="mode"><option value="due">Fällige</option><option value="new">Neue</option><option value="errors">Fehlerkarten</option><option value="all">Alle</option></select><select id="topic"><option value="all">Alle Themen</option>${topics.map(t=>`<option>${esc(t)}</option>`).join('')}</select><button class="btn primary" data-custom>Starten</button></div></section>`)}
function session(){if(!current)return frame(`<section class="card"><h2>Sitzung beendet</h2><button class="btn primary" data-view="dashboard">Zur Übersicht</button></section>`);const p=progress(current);const input=`<textarea id="answer" class="answerbox" placeholder="Antwort oder Notizen eingeben">${esc(answerText)}</textarea>`;let solution='';if(revealed){const terms=current.answer.requiredTerms??current.answer.criteria??[];const ok=current.questionType==='numeric'?Number(answerText.replace(',','.'))===current.answer.value:terms.every(t=>norm(answerText).includes(norm(t)));solution=`<div class="solution"><strong>Musterlösung</strong><p>${esc(current.answer.modelAnswer)}</p><div>${terms.map(t=>`<span class="term ${norm(answerText).includes(norm(t))?'':'missing'}">${esc(t)}</span>`).join('')}</div><p>Automatische Einschätzung: ${ok?'eher passend':'unvollständig'}; finale Bewertung durch dich.</p><p class="muted">Quelle: ${esc(current.source)} · Prüfungsfrage ${esc(current.examQuestion)}</p></div><div class="actions"><button class="btn bad" data-grade="incorrect">Falsch</button><button class="btn warn" data-grade="partial">Teilweise</button><button class="btn good" data-grade="correct">Richtig</button></div>`}return frame(`<div class="toolbar"><span class="pill">${esc(current.topicId)}</span><span class="pill">Stufe ${p.stage}</span><span class="pill">Frage ${esc(current.examQuestion)}</span><span class="muted">${queue.length+retry.length} verbleibend</span></div><section class="card"><div class="question">${esc(current.prompt)}</div><div style="margin-top:1rem">${input}</div><div class="actions"><button class="btn" data-skip>Überspringen</button><button class="btn" data-mark>${p.marked?'Markierung entfernen':'Markieren'}</button>${revealed?'':'<button class="btn primary" data-reveal>Lösung zeigen</button>'}</div>${solution}</section>`)}
function exam(){return frame(`<section class="card"><h2>Prüfungssimulation</h2><p>Bis zu 57 freigegebene Aufgaben werden zufällig zusammengestellt. Das endgültige 202-Punkte-Profil folgt mit der vollständigen Katalogredaktion.</p><button class="btn primary" data-exam>Simulation starten</button></section>`)}
function stats(){const m=metrics();return frame(`<section class="card"><h2>Statistik</h2><table class="table"><tr><th>Karte</th><th>Stufe</th><th>R</th><th>T</th><th>F</th><th>Fällig</th></tr>${m.all.map(c=>{const p=progress(c);return `<tr><td>${c.id}</td><td>${p.stage}</td><td>${p.correct}</td><td>${p.partial}</td><td>${p.incorrect}</td><td>${due(p)?'ja':'nein'}</td></tr>`}).join('')}</table></section>`)}
function reviewView(){return frame(`<section class="card"><h2>Redaktioneller Review</h2><p>${cards.filter(c=>c.status==='needs_review').length} Karten benötigen Quellen- oder Bildprüfung. Statusänderungen werden lokal protokolliert, ändern aber nicht den eingebauten Katalog.</p><table class="table"><tr><th>ID</th><th>Frage</th><th>Status</th></tr>${cards.map(c=>`<tr><td>${c.id}</td><td>${esc(c.prompt)}</td><td>${state.review[c.id]??c.status}</td></tr>`).join('')}</table></section>`)}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({format:'etf-backup',version:1,createdAt:new Date().toISOString(),state},null,2)],{type:'application/json'}));a.download='etf-backup.json';a.click();URL.revokeObjectURL(a.href)}
function dataView(){return frame(`<section class="card"><h2>Daten</h2><div class="actions"><button class="btn primary" data-export>Backup exportieren</button><label class="btn">Backup importieren<input id="import" hidden type="file" accept="application/json"></label><button class="btn bad" data-reset>Alles zurücksetzen</button></div></section>`)}
function render(){const app=document.querySelector('#app')!;app.innerHTML=view==='dashboard'?dashboard():view==='learn'?setup():view==='session'?session():view==='exam'?exam():view==='stats'?stats():view==='review'?reviewView():dataView();document.querySelectorAll('[data-view]').forEach(e=>e.addEventListener('click',()=>{view=(e as HTMLElement).dataset.view!;current=undefined;render()}));document.querySelectorAll('[data-start]').forEach(e=>e.addEventListener('click',()=>start((e as HTMLElement).dataset.start!)));document.querySelector('[data-custom]')?.addEventListener('click',()=>{topic=(document.querySelector('#topic') as HTMLSelectElement).value;start((document.querySelector('#mode') as HTMLSelectElement).value)});document.querySelector('[data-reveal]')?.addEventListener('click',()=>{answerText=(document.querySelector('#answer') as HTMLTextAreaElement).value;revealed=true;render()});document.querySelectorAll('[data-grade]').forEach(e=>e.addEventListener('click',()=>grade((e as HTMLElement).dataset.grade as Outcome)));document.querySelector('[data-skip]')?.addEventListener('click',()=>{queue.push(current!);next()});document.querySelector('[data-mark]')?.addEventListener('click',()=>{const p=progress(current!);p.marked=!p.marked;state.progress[current!.id]=p;save();render()});document.querySelector('[data-exam]')?.addEventListener('click',()=>{queue=cards.filter(c=>c.status==='released').sort(()=>Math.random()-.5).slice(0,57);retry=[];view='session';next()});document.querySelector('[data-export]')?.addEventListener('click',download);document.querySelector('#import')?.addEventListener('change',async e=>{try{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;const x=JSON.parse(await f.text());if(x.format!=='etf-backup'||!x.state)throw Error('Ungültiges Backup');state=x.state;save();render()}catch(err){alert(String(err))}});document.querySelector('[data-reset]')?.addEventListener('click',()=>{if(confirm('Vor dem Reset wird ein Backup exportiert. Fortfahren?')){download();state={progress:{},history:[],review:{}};save();render()}})}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');render();
