import './v04.css';
import { loadState, saveState, type PersistedState } from './db';
import { builtinCatalog } from './builtin-v04';
import { applyReview } from './review-engine';
import { calculateReadiness, createEqualWeightBlueprint, validateExamBlueprint } from './exam-intelligence';
import { buildTodayPlan } from './today-plan';
import { analyzeLearningDiagnostics, type LearningDiagnosticCode, type LearningInterventionCode } from './diagnostics';
import { readinessTrend, recordReadinessSnapshot } from './readiness-history';
import { legacyQuestionVariantId, type AppState, type CardVersion, type Catalog, type ExamBlueprint, type Outcome, type Progress, type QuestionType, type QueueReasonCode } from './model';

const $ = <T extends Element>(s:string) => document.querySelector<T>(s);
const esc = (v:unknown) => String(v ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!));
const now = () => new Date().toISOString();
const questionTypes:QuestionType[]=['free_text','numeric','single_choice','multiple_choice','cloze','matching','ordering','image_labels','drawing','case_study'];
const labels:Record<QuestionType,string>={free_text:'Freitext',numeric:'Zahl',single_choice:'Single Choice',multiple_choice:'Multiple Choice',cloze:'Lückentext',matching:'Zuordnung',ordering:'Reihenfolge',image_labels:'Bildbeschriftung',drawing:'Zeichnung',case_study:'Fallaufgabe'};
const reasonLabels:Record<QueueReasonCode,string>={CLASSIC_DUE:'klassisch fällig',FSRS_SHADOW_DUE:'FSRS-Shadow fällig (ohne Einfluss)',LOW_MASTERY:'niedrige Lernstufe',HIGH_EXAM_WEIGHT:'hohe Prüfungsgewichtung',COVERAGE_GAP:'noch nicht abgedeckt',EXAM_SOON:'Prüfung rückt näher',RECENT_FAILURE:'zuletzt unsicher oder falsch',NEW_CONTENT:'neuer Inhalt'};
const diagnosticLabels:Record<LearningDiagnosticCode,string>={REPEATED_FAILURE:'wiederholte Fehler',REPEATED_UNCERTAINTY:'wiederholte Unsicherheit',SLOW_RECALL:'langsamer Abruf',EXAM_FAILURE:'Fehler in Prüfungssimulation',LOW_MASTERY_AFTER_REVIEWS:'niedrige Stufe trotz vieler Reviews',REGRESSION_AFTER_SUCCESS:'Rückfall nach früherem Erfolg'};
const interventionLabels:Record<LearningInterventionCode,string>={REVIEW_EXPLANATION:'Erklärung und Musterlösung gezielt prüfen',TRY_ALTERNATE_VARIANT:'eine alternative Fragevariante bearbeiten',SHORT_RECALL_DRILL:'kurze Abrufübung ohne Hilfen durchführen',RETEST_UNDER_EXAM_CONDITIONS:'nach Wiederholung erneut unter Prüfungsbedingungen testen',BREAK_DOWN_KNOWLEDGE_ITEM:'Wissenseinheit in kleinere Grundlagenfragen zerlegen',COMPARE_WITH_PRIOR_SUCCESS:'mit früherem erfolgreichen Lösungsweg vergleichen'};

let state:AppState;
let view='home';
let queue:CardVersion[]=[];
let queueReasons=new Map<string,QueueReasonCode[]>();
let current:CardVersion|undefined;
let revealed=false;
let sessionIndex=0;
let editorCardId:string|undefined;
let catalogQuery='';
let examMode=false;
let questionStartedAt=Date.now();

function defaultState():AppState{return {schemaVersion:3,progress:{},history:[],reviewEvents:[],fsrsShadow:{},review:{},sessions:{},examAttempts:[],migrationLog:[],catalogs:[structuredClone(builtinCatalog)],activeCatalogId:builtinCatalog.catalogId,readinessSnapshots:[]};}
function migrate(raw:PersistedState):AppState{
  const r=raw as unknown as Partial<AppState>&{activeCatalog?:{catalogId?:string;version?:string;cards?:CardVersion[]}};
  const catalogs=Array.isArray(r.catalogs)&&r.catalogs.length?r.catalogs:[];
  if(!catalogs.length&&r.activeCatalog?.cards?.length)catalogs.push({catalogId:r.activeCatalog.catalogId??'imported',title:r.activeCatalog.catalogId??'Importierter Katalog',version:r.activeCatalog.version??'1.0.0',createdAt:now(),updatedAt:now(),cards:r.activeCatalog.cards});
  if(!catalogs.length)catalogs.push(structuredClone(builtinCatalog));
  return {...defaultState(),...r,reviewEvents:Array.isArray(r.reviewEvents)?r.reviewEvents:[],fsrsShadow:r.fsrsShadow??{},readinessSnapshots:Array.isArray(r.readinessSnapshots)?r.readinessSnapshots:[],catalogs,activeCatalogId:r.activeCatalogId??catalogs[0].catalogId,schemaVersion:3} as AppState;
}
const persist=()=>saveState(state as unknown as PersistedState);
const activeCatalog=()=>state.catalogs.find(c=>c.catalogId===state.activeCatalogId)??state.catalogs[0];
const activeCards=()=>activeCatalog().cards.filter(c=>c.status==='released');
const progress=(c:CardVersion):Progress=>state.progress[c.id]??{stage:1,dueAt:new Date(0).toISOString(),correct:0,partial:0,incorrect:0,skipped:0,marked:false,cardVersion:c.version};
const due=(p:Progress)=>new Date(p.dueAt).getTime()<=Date.now();

function currentReadiness(calculatedAt=new Date()){const cat=activeCatalog(),cards=activeCards();if(!cards.length)return undefined;try{return calculateReadiness({catalogId:cat.catalogId,cards,progress:state.progress,blueprint:cat.examBlueprint,calculatedAt});}catch{return calculateReadiness({catalogId:cat.catalogId,cards,progress:state.progress,calculatedAt});}}
function recordCurrentReadiness(calculatedAt=new Date()){const snapshot=currentReadiness(calculatedAt);if(snapshot)recordReadinessSnapshot(state,snapshot);return snapshot;}
function currentTodayPlan(){const cat=activeCatalog(),cards=activeCards();if(!cards.length)return undefined;const input={catalogId:cat.catalogId,cards,progress:state.progress,reviewEvents:state.reviewEvents,fsrsShadow:state.fsrsShadow,blueprint:cat.examBlueprint,now:new Date()};try{return buildTodayPlan(input);}catch{return buildTodayPlan({...input,blueprint:undefined});}}
function editableBlueprint(){const cat=activeCatalog(),cards=activeCards();if(!cards.length)return undefined;const base=cat.examBlueprint??createEqualWeightBlueprint(cat.catalogId,cards);const weights=new Map(base.sections.map(section=>[section.topicId,section.weight]));const topics=[...new Set(cards.map(card=>card.topicId))].sort();return {...base,sections:topics.map(topicId=>({topicId,weight:weights.get(topicId)??1}))};}
function icon(name:string){const map:Record<string,string>={home:'⌂',learn:'▶',exam:'✓',progress:'◫',catalogs:'▤',settings:'⚙'};return map[name]??'•'}
function nav(){const items=[['home','Start'],['learn','Lernen'],['exam','Prüfung'],['progress','Fortschritt'],['catalogs','Kataloge'],['settings','Einstellungen']];return `<nav class="bottom-nav">${items.map(([id,label])=>`<button data-view="${id}" class="${view===id?'active':''}"><span>${icon(id)}</span><small>${label}</small></button>`).join('')}</nav>`}
function shell(content:string){const cat=activeCatalog();return `<div class="app-shell"><header class="app-header"><div><div class="eyebrow">Exam Trainer Framework</div><h1>${esc(cat.title)}</h1></div><span class="status-pill">● offlinefähig</span></header><main>${content}</main>${nav()}</div>`}
function metric(label:string,value:string,sub=''){return `<article class="metric-card"><span>${label}</span><strong>${value}</strong>${sub?`<small>${sub}</small>`:''}</article>`}

function home(){const cards=activeCards(),ps=cards.map(progress),plan=currentTodayPlan(),readiness=currentReadiness();const dueCount=ps.filter(due).length,newCount=cards.filter(c=>!state.progress[c.id]).length;const planText=plan?`${plan.review} Wiederholungen · ${plan.weakness} Schwachstellen · ${plan.newContent} neue Inhalte · ca. ${plan.estimatedMinutes} Min.`:'Noch keine freigegebenen Lerninhalte.';return shell(`<section class="hero"><span class="eyebrow">Heute</span><h2>${plan?.items.length?`${plan.items.length} Aufgaben für heute`:'Alles erledigt'}</h2><p>${esc(planText)}</p><button class="primary large" data-start-today ${plan?.items.length?'':'disabled'}>Heute lernen</button></section><section class="metrics">${metric('Readiness',readiness?`${readiness.readiness}%`:'–',readiness?.weakestTopicId?`Schwächster Bereich: ${esc(readiness.weakestTopicId)}`:'')}${metric('Coverage',readiness?`${readiness.coverage}%`:'–')}${metric('Fällig',String(plan?.due??dueCount))}${metric('Neu',String(newCount))}</section><section class="panel"><div class="section-head"><div><span class="eyebrow">Schnellzugriff</span><h2>Was möchtest du tun?</h2></div></div><div class="quick-grid"><button data-view="learn">Lernsitzung konfigurieren</button><button data-view="exam">Prüfung simulieren</button><button data-view="catalogs">Fragenkatalog bearbeiten</button><button data-view="progress">Fortschritt ansehen</button></div></section>`)}
function learn(){const topics=[...new Set(activeCards().map(c=>c.topicId))];return shell(`<section class="panel"><span class="eyebrow">Lernen</span><h2>Neue Sitzung</h2><label>Lernmodus<select id="mode"><option value="due">Fällige Karten</option><option value="new">Neue Karten</option><option value="errors">Fehlerkarten</option><option value="all">Alle Karten</option></select></label><label>Thema<select id="topic"><option value="all">Alle Themen</option>${topics.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('')}</select></label><button class="primary large" data-start-custom>Sitzung starten</button></section>`)}
function startToday(){const plan=currentTodayPlan();if(!plan?.items.length)return;const byId=new Map(activeCards().map(card=>[card.id,card]));queue=plan.items.map(item=>byId.get(item.cardId)).filter((card):card is CardVersion=>Boolean(card));queueReasons=new Map(plan.items.map(item=>[item.cardId,item.reasons]));sessionIndex=0;examMode=false;view='session';next();}
function start(mode:string,topic='all'){const all=activeCards().filter(c=>topic==='all'||c.topicId===topic);queue=mode==='new'?all.filter(c=>!state.progress[c.id]):mode==='errors'?all.filter(c=>progress(c).incorrect>0):mode==='all'?[...all]:all.filter(c=>due(progress(c)));if(!queue.length)queue=all.slice(0,10);queue.sort(()=>Math.random()-.5);queueReasons=new Map();sessionIndex=0;examMode=false;view='session';next();}
function next(){current=queue.shift();revealed=false;sessionIndex++;if(current)questionStartedAt=Date.now();render();}
function advisory(c:CardVersion,text:string){if(c.questionType==='numeric'&&c.answer.value!==undefined){const n=Number(text.replace(',','.'));const tol=c.answer.tolerance??{type:'absolute' as const,value:0};const ok=tol.type==='absolute'?Math.abs(n-c.answer.value)<=tol.value:Math.abs(n-c.answer.value)/Math.abs(c.answer.value)<=tol.value;return ok?'Zahlenwert liegt innerhalb der Toleranz.':'Zahlenwert liegt außerhalb der Toleranz.'}const normalized=text.toLowerCase();const missing=(c.answer.requiredTerms??[]).filter(t=>!normalized.includes(t.toLowerCase()));return missing.length?`Noch nicht erkannt: ${missing.join(', ')}`:'Alle Pflichtbegriffe erkannt.'}
function session(){if(!current)return shell(`<section class="panel centered"><div class="success">✓</div><h2>Sitzung abgeschlossen</h2><p>Dein Lernstand wurde lokal gespeichert.</p><button class="primary" data-view="home">Zur Startseite</button></section>`);const total=sessionIndex+queue.length;const p=progress(current),reasons=queueReasons.get(current.id)??[];const why=reasons.length?`<details><summary>Warum diese Frage?</summary><p>${reasons.map(reason=>esc(reasonLabels[reason])).join(' · ')}</p></details>`:'';return shell(`<section class="session"><div class="session-top"><span>${sessionIndex} von ${total}</span><span>${esc(current.topicId)} · ${current.points} P</span></div><div class="bar"><i style="width:${Math.round(sessionIndex/total*100)}%"></i></div><article class="question-card"><span class="eyebrow">${labels[current.questionType]}</span><h2>${esc(current.prompt)}</h2>${why}${current.questionType==='drawing'?'<div class="drawing-hint">Zeichnung auf Papier oder in einer Zeichen-App anfertigen.</div>':`<textarea id="answer" rows="7" placeholder="Deine Antwort …"></textarea>`}${revealed?`<div class="answer-box"><span class="eyebrow">Musterlösung</span><p>${esc(current.answer.modelAnswer)}</p><small id="advisory"></small></div><div class="grade-grid"><button class="danger" data-grade="incorrect">Nicht gewusst</button><button data-grade="partial">Unsicher</button><button class="primary" data-grade="correct">Gewusst</button></div>`:`<div class="question-actions"><button data-skip>Später</button><button data-mark>${p.marked?'Markierung entfernen':'Markieren'}</button><button class="primary" data-reveal>Lösung zeigen</button></div>`}</article></section>`)}
function grade(outcome:Outcome){if(!current)return;const answeredAt=new Date();applyReview(state,{knowledgeItemId:current.id,questionVariantId:legacyQuestionVariantId(current.id),cardVersion:current.version},outcome,examMode?'exam':'learning',answeredAt,Math.max(0,answeredAt.getTime()-questionStartedAt),{fsrsShadowEnabled:true});recordCurrentReadiness(answeredAt);void persist();next();}
function exam(){const cat=activeCatalog(),last=state.examAttempts.at(-1),bp=editableBlueprint();const fallback=!cat.examBlueprint;const rows=bp?.sections.map(section=>`<tr><td>${esc(section.topicId)}</td><td><input type="number" min="0.01" step="0.01" value="${section.weight}" data-blueprint-weight="${esc(section.topicId)}"></td></tr>`).join('')??'';return shell(`<section class="panel"><span class="eyebrow">Prüfung</span><h2>Prüfungsprofil</h2><p>${fallback?'Aktuell wird eine gleichmäßige Themengewichtung verwendet. Speichere ein Blueprint, um die echte Prüfungsverteilung zu hinterlegen.':'Dieses Blueprint steuert Readiness und die adaptive Lernpriorisierung.'}</p><div class="form-grid"><label>Prüfungstermin<input id="exam-date" type="date" value="${esc(bp?.examDate?.slice(0,10)??'')}"></label><label>Bestehensgrenze (%)<input id="pass-threshold" type="number" min="0" max="100" step="0.1" value="${bp?.passThreshold===undefined?'':bp.passThreshold*100}"></label><label>Aufgaben gesamt<input id="exam-items" type="number" min="1" step="1" value="${bp?.totalItems??''}"></label><label>Punkte gesamt<input id="exam-points" type="number" min="0.01" step="0.01" value="${bp?.totalPoints??''}"></label><label>Zeitlimit (Min.)<input id="exam-time" type="number" min="1" step="1" value="${bp?.timeLimitMinutes??''}"></label></div><p class="muted">Themengewichte sind relative Werte; 30/20/50 ist ebenso gültig wie 3/2/5.</p><div class="table-scroll"><table><thead><tr><th>Thema</th><th>Gewicht</th></tr></thead><tbody>${rows}</tbody></table></div><div class="question-actions"><button class="primary" data-save-blueprint>Blueprint speichern</button>${cat.examBlueprint?'<button data-clear-blueprint>Auf Gleichgewicht zurücksetzen</button>':''}</div></section><section class="panel"><h2>Simulation</h2><p>Feste oder dynamische Prüfung. Abhängige Teilaufgaben bleiben in ihrer Reihenfolge zusammen.</p><label>Modus<select id="exam-mode"><option value="dynamic">Dynamisch nach Themen</option><option value="fixed">Festes 57/202-Profil</option></select></label><button class="primary large" data-exam>Prüfung starten</button>${last?`<div class="result-card"><span>Letztes Ergebnis</span><strong>${last.points} / ${last.maxPoints}</strong><small>${last.percentage}%</small></div>`:''}</section>`)}
function saveBlueprint(){const cat=activeCatalog(),cards=activeCards();if(!cards.length)return;const previous=cat.examBlueprint;const sections=Array.from(document.querySelectorAll<HTMLInputElement>('[data-blueprint-weight]')).map(input=>({topicId:input.dataset.blueprintWeight??'',weight:Number(input.value)}));const optionalNumber=(selector:string)=>{const value=$<HTMLInputElement>(selector)?.value.trim()??'';return value===''?undefined:Number(value);};const date=$<HTMLInputElement>('#exam-date')?.value.trim()??'';const threshold=optionalNumber('#pass-threshold');const blueprint:ExamBlueprint={id:previous?.id??`${cat.catalogId}:primary`,catalogId:cat.catalogId,version:(previous?.version??0)+1,title:'Prüfungs-Blueprint',examDate:date||undefined,totalItems:optionalNumber('#exam-items'),totalPoints:optionalNumber('#exam-points'),timeLimitMinutes:optionalNumber('#exam-time'),passThreshold:threshold===undefined?undefined:threshold/100,sections};const errors=validateExamBlueprint(blueprint,cards);if(errors.length)return alert(errors.join('\n'));cat.examBlueprint=blueprint;cat.updatedAt=now();recordCurrentReadiness(new Date());void persist();alert('Prüfungs-Blueprint gespeichert. Readiness und Tagesplan wurden aktualisiert.');render();}
function startExam(){const source=activeCards();if(!source.length)return;queue=[...source].sort(()=>Math.random()-.5).slice(0,Math.min(57,source.length));queueReasons=new Map();sessionIndex=0;examMode=true;view='session';next();}
function progressView(){const cards=activeCards(),readiness=currentReadiness(),trend=readinessTrend(state.readinessSnapshots??[],activeCatalog().catalogId),cardIds=new Set(cards.map(card=>card.id));const diagnostics=analyzeLearningDiagnostics(state.reviewEvents,state.progress).filter(item=>cardIds.has(item.knowledgeItemId)).slice(0,10);const trendText=trend.delta===undefined?'noch kein Verlauf':`${trend.delta>=0?'+':''}${trend.delta} Punkte`;const diagnosticRows=diagnostics.map(item=>`<tr><td>${esc(item.knowledgeItemId)}</td><td>${item.leech?'Leech':'beobachten'}</td><td>${item.codes.map(code=>esc(diagnosticLabels[code])).join(' · ')}</td><td>${item.interventions.map(code=>esc(interventionLabels[code])).join(' · ')}</td></tr>`).join('');return shell(`<section class="metrics">${metric('Readiness',readiness?`${readiness.readiness}%`:'–')}${metric('Trend',trendText)}${metric('Coverage',readiness?`${readiness.coverage}%`:'–')}${metric('Problemkarten',String(diagnostics.filter(item=>item.leech).length))}</section><section class="panel"><span class="eyebrow">Diagnostik</span><h2>Auffällige Lernmuster</h2><p class="muted">Die Hinweise beruhen nur auf beobachtbaren Review-Mustern. Die Empfehlungen sind Vorschläge und führen keine Aktion automatisch aus.</p>${diagnosticRows?`<div class="table-scroll"><table><thead><tr><th>Karte</th><th>Status</th><th>Beobachtung</th><th>Empfohlene nächste Aktion</th></tr></thead><tbody>${diagnosticRows}</tbody></table></div>`:'<p>Aktuell keine auffälligen Muster.</p>'}</section><section class="panel"><span class="eyebrow">Fortschritt</span><h2>Dein Lernstand</h2><div class="stage-list">${[1,2,3,4,5].map(s=>`<div><span>Stufe ${s}</span><strong>${cards.filter(c=>progress(c).stage===s).length}</strong></div>`).join('')}</div></section><section class="panel"><h2>Karten</h2><div class="table-scroll"><table><thead><tr><th>ID</th><th>Thema</th><th>Stufe</th><th>R/T/F</th></tr></thead><tbody>${cards.map(c=>{const p=progress(c);return `<tr><td>${esc(c.id)}</td><td>${esc(c.topicId)}</td><td>${p.stage}</td><td>${p.correct}/${p.partial}/${p.incorrect}</td></tr>`}).join('')}</tbody></table></div></section>`)}

function catalogStats(c:Catalog){return {released:c.cards.filter(x=>x.status==='released').length,draft:c.cards.filter(x=>x.status==='draft').length,review:c.cards.filter(x=>['in_review','changes_requested','approved'].includes(x.status)).length};}
function catalogs(){const cat=activeCatalog();const list=cat.cards.filter(c=>!catalogQuery||`${c.id} ${c.prompt} ${c.topicId}`.toLowerCase().includes(catalogQuery.toLowerCase()));const s=catalogStats(cat);return shell(`<section class="panel"><div class="section-head"><div><span class="eyebrow">Katalogverwaltung</span><h2>${esc(cat.title)}</h2><p>Version ${esc(cat.version)} · ${s.released} freigegeben · ${s.draft} Entwürfe · ${s.review} im Workflow</p></div><button class="primary" data-new-card>+ Karte</button></div><div class="catalog-switch"><select id="catalog-select">${state.catalogs.filter(c=>!c.archived).map(c=>`<option value="${esc(c.catalogId)}" ${c.catalogId===state.activeCatalogId?'selected':''}>${esc(c.title)}</option>`).join('')}</select><button data-new-catalog>Neuer Katalog</button><button data-duplicate-catalog>Duplizieren</button></div><input id="catalog-search" type="search" value="${esc(catalogQuery)}" placeholder="Karten durchsuchen …"><div class="card-list">${list.map(c=>`<button class="card-row" data-edit-card="${esc(c.id)}"><span><strong>${esc(c.prompt)}</strong><small>${esc(c.id)} · ${esc(c.topicId)} · ${labels[c.questionType]}</small></span><em class="status ${c.status}">${c.status}</em></button>`).join('')||'<p class="empty">Keine Karten gefunden.</p>'}</div></section>`)}
function blankCard():CardVersion{return {id:`card-${crypto.randomUUID().slice(0,8)}`,version:1,status:'draft',topicId:'Allgemein',examQuestion:'',prompt:'',points:1,difficulty:2,tags:[],questionType:'free_text',answer:{modelAnswer:'',requiredTerms:[]},source:'',changedAt:now()};}
function editor(){const cat=activeCatalog();const card=cat.cards.find(c=>c.id===editorCardId)??blankCard();const isNew=!cat.cards.some(c=>c.id===editorCardId);return shell(`<section class="editor"><div class="editor-head"><button data-view="catalogs">← Zurück</button><div><span class="eyebrow">${isNew?'Neue Karte':'Karte bearbeiten'}</span><h2>${esc(card.id)}</h2></div><button class="primary" data-save-card>Speichern</button></div><div class="editor-grid"><form id="card-form" class="panel"><div class="form-grid"><label>ID<input name="id" value="${esc(card.id)}" ${isNew?'':'readonly'}></label><label>Status<select name="status">${['draft','in_review','changes_requested','approved','released','retired'].map(s=>`<option ${s===card.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Thema<input name="topicId" value="${esc(card.topicId)}"></label><label>Prüfungsfrage<input name="examQuestion" value="${esc(card.examQuestion)}"></label><label>Fragetyp<select name="questionType">${questionTypes.map(t=>`<option value="${t}" ${t===card.questionType?'selected':''}>${labels[t]}</option>`).join('')}</select></label><label>Punkte<input name="points" type="number" min="0" step="1" value="${card.points}"></label><label>Schwierigkeit<select name="difficulty">${[1,2,3,4,5].map(x=>`<option ${x===card.difficulty?'selected':''}>${x}</option>`).join('')}</select></label><label>Tags<input name="tags" value="${esc(card.tags.join(', '))}"></label></div><label>Frage<textarea name="prompt" rows="4">${esc(card.prompt)}</textarea></label><label>Musterlösung<textarea name="modelAnswer" rows="5">${esc(card.answer.modelAnswer)}</textarea></label><label>Pflichtbegriffe<input name="requiredTerms" value="${esc((card.answer.requiredTerms??[]).join(', '))}"></label><div class="form-grid"><label>Zahlenwert<input name="value" type="number" step="any" value="${card.answer.value??''}"></label><label>Absolute Toleranz<input name="tolerance" type="number" step="any" value="${card.answer.tolerance?.value??0}"></label></div><label>Quelle<input name="source" value="${esc(card.source)}"></label><label>Seite / Abschnitt<input name="sourcePage" value="${esc(card.sourcePage??'')}"></label><label>Änderungsgrund<input name="changeReason" value="${esc(card.changeReason??'')}"></label><div class="editor-actions"><button type="button" class="danger" data-delete-card ${isNew?'disabled':''}>Löschen</button><button type="button" data-duplicate-card ${isNew?'disabled':''}>Duplizieren</button><button type="button" data-json-card>JSON</button></div></form><aside class="panel preview"><span class="eyebrow">Live-Vorschau</span><h2 id="preview-prompt">${esc(card.prompt||'Fragevorschau')}</h2><div class="preview-answer"><small>Musterlösung</small><p id="preview-answer">${esc(card.answer.modelAnswer||'Noch keine Musterlösung')}</p></div><p><small>${labels[card.questionType]} · ${card.points} Punkte</small></p></aside></div></section>`)}
function settings(){return shell(`<section class="panel"><span class="eyebrow">Einstellungen</span><h2>Daten und Sicherung</h2><div class="settings-list"><button data-export>Backup exportieren</button><label class="button-like">Backup importieren<input id="backup-import" hidden type="file" accept="application/json"></label><label class="button-like">Katalog importieren<input id="catalog-import" hidden type="file" accept="application/json"></label><button class="danger" data-reset>Lokale Daten zurücksetzen</button></div><p class="muted">Letztes Backup: ${state.lastBackupAt?new Date(state.lastBackupAt).toLocaleString('de-DE'):'noch keines'}</p></section>`)}
function validateCard(c:CardVersion){const e:string[]=[];if(!c.id.trim())e.push('ID fehlt');if(!c.prompt.trim())e.push('Frage fehlt');if(!c.answer.modelAnswer.trim())e.push('Musterlösung fehlt');if(c.points<0)e.push('Punkte sind ungültig');if(c.status==='released'&&!c.source.trim())e.push('Freigegebene Karten benötigen eine Quelle');return e;}
function formCard():CardVersion{const form=$<HTMLFormElement>('#card-form')!;const fd=new FormData(form);const existing=activeCatalog().cards.find(c=>c.id===editorCardId);const status=String(fd.get('status')) as CardVersion['status'];const publishedEdit=existing?.status==='released';return {id:String(fd.get('id')).trim(),version:publishedEdit?(existing!.version+1):(existing?.version??1),status:publishedEdit?'draft':status,topicId:String(fd.get('topicId')).trim(),examQuestion:String(fd.get('examQuestion')).trim(),prompt:String(fd.get('prompt')).trim(),points:Number(fd.get('points')||0),difficulty:Number(fd.get('difficulty')) as CardVersion['difficulty'],tags:String(fd.get('tags')).split(',').map(x=>x.trim()).filter(Boolean),questionType:String(fd.get('questionType')) as QuestionType,answer:{modelAnswer:String(fd.get('modelAnswer')).trim(),requiredTerms:String(fd.get('requiredTerms')).split(',').map(x=>x.trim()).filter(Boolean),value:fd.get('value')!==''?Number(fd.get('value')):undefined,tolerance:{type:'absolute',value:Number(fd.get('tolerance')||0)}},source:String(fd.get('source')).trim(),sourcePage:String(fd.get('sourcePage')).trim(),changeReason:String(fd.get('changeReason')).trim(),changedAt:now(),parentId:publishedEdit?existing!.id:existing?.parentId};}
function download(name:string,data:unknown){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}

function render(){const app=$<HTMLElement>('#app')!;app.innerHTML=view==='home'?home():view==='learn'?learn():view==='session'?session():view==='exam'?exam():view==='progress'?progressView():view==='catalogs'?catalogs():view==='editor'?editor():settings();bind();}
function bind(){document.querySelectorAll<HTMLElement>('[data-view]').forEach(el=>el.onclick=()=>{view=el.dataset.view!;render();});document.querySelectorAll<HTMLElement>('[data-start]').forEach(el=>el.onclick=()=>start(el.dataset.start!));$<HTMLElement>('[data-start-today]')?.addEventListener('click',startToday);$<HTMLElement>('[data-start-custom]')?.addEventListener('click',()=>start($<HTMLSelectElement>('#mode')!.value,$<HTMLSelectElement>('#topic')!.value));$<HTMLElement>('[data-reveal]')?.addEventListener('click',()=>{revealed=true;render();setTimeout(()=>{const text=$<HTMLTextAreaElement>('#answer')?.value??'';const adv=$<HTMLElement>('#advisory');if(adv&&current)adv.textContent=advisory(current,text);});});document.querySelectorAll<HTMLElement>('[data-grade]').forEach(el=>el.onclick=()=>grade(el.dataset.grade as Outcome));$<HTMLElement>('[data-skip]')?.addEventListener('click',()=>{if(current){const p=progress(current);p.skipped++;state.progress[current.id]=p;queue.push(current);void persist();next();}});$<HTMLElement>('[data-mark]')?.addEventListener('click',()=>{if(current){const p=progress(current);p.marked=!p.marked;state.progress[current.id]=p;void persist();render();}});$<HTMLElement>('[data-exam]')?.addEventListener('click',startExam);$<HTMLElement>('[data-save-blueprint]')?.addEventListener('click',saveBlueprint);$<HTMLElement>('[data-clear-blueprint]')?.addEventListener('click',()=>{const cat=activeCatalog();delete cat.examBlueprint;cat.updatedAt=now();recordCurrentReadiness(new Date());void persist();render();});
$<HTMLSelectElement>('#catalog-select')?.addEventListener('change',e=>{state.activeCatalogId=(e.target as HTMLSelectElement).value;void persist();render();});$<HTMLInputElement>('#catalog-search')?.addEventListener('input',e=>{catalogQuery=(e.target as HTMLInputElement).value;render();});document.querySelectorAll<HTMLElement>('[data-edit-card]').forEach(el=>el.onclick=()=>{editorCardId=el.dataset.editCard;view='editor';render();});$<HTMLElement>('[data-new-card]')?.addEventListener('click',()=>{editorCardId=undefined;view='editor';render();});$<HTMLElement>('[data-new-catalog]')?.addEventListener('click',()=>{const title=prompt('Name des neuen Katalogs:');if(!title)return;const id=`catalog-${crypto.randomUUID().slice(0,8)}`;state.catalogs.push({catalogId:id,title,version:'0.1.0',createdAt:now(),updatedAt:now(),cards:[]});state.activeCatalogId=id;void persist();render();});$<HTMLElement>('[data-duplicate-catalog]')?.addEventListener('click',()=>{const c=structuredClone(activeCatalog());c.catalogId=`${c.catalogId}-copy-${Date.now()}`;c.title+= ' – Kopie';c.version='0.1.0';c.createdAt=c.updatedAt=now();state.catalogs.push(c);state.activeCatalogId=c.catalogId;void persist();render();});
$<HTMLFormElement>('#card-form')?.addEventListener('input',()=>{const fd=new FormData($<HTMLFormElement>('#card-form')!);$<HTMLElement>('#preview-prompt')!.textContent=String(fd.get('prompt')||'Fragevorschau');$<HTMLElement>('#preview-answer')!.textContent=String(fd.get('modelAnswer')||'Noch keine Musterlösung');});$<HTMLElement>('[data-save-card]')?.addEventListener('click',()=>{const c=formCard(),errors=validateCard(c);if(errors.length)return alert(errors.join('\n'));const cat=activeCatalog(),idx=cat.cards.findIndex(x=>x.id===editorCardId);if(idx>=0&&cat.cards[idx].status==='released')cat.cards.push(c);else if(idx>=0)cat.cards[idx]=c;else cat.cards.push(c);cat.updatedAt=now();editorCardId=c.id;void persist();view='catalogs';render();});$<HTMLElement>('[data-delete-card]')?.addEventListener('click',()=>{if(!editorCardId||!confirm('Karte löschen?'))return;const cat=activeCatalog();cat.cards=cat.cards.filter(c=>c.id!==editorCardId);void persist();view='catalogs';render();});$<HTMLElement>('[data-duplicate-card]')?.addEventListener('click',()=>{const c=activeCatalog().cards.find(x=>x.id===editorCardId);if(!c)return;const copy=structuredClone(c);copy.id=`${c.id}-copy`;copy.version=1;copy.status='draft';copy.changedAt=now();activeCatalog().cards.push(copy);editorCardId=copy.id;void persist();render();});$<HTMLElement>('[data-json-card]')?.addEventListener('click',()=>alert(JSON.stringify(formCard(),null,2)));
$<HTMLElement>('[data-export]')?.addEventListener('click',()=>{state.lastBackupAt=now();void persist();download(`etf-backup-${new Date().toISOString().slice(0,10)}.json`,{format:'etf-backup',version:3,state});render();});$<HTMLInputElement>('#backup-import')?.addEventListener('change',async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;const x=JSON.parse(await f.text());state=migrate(x.state as PersistedState);await persist();render();});$<HTMLInputElement>('#catalog-import')?.addEventListener('change',async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;const c=JSON.parse(await f.text()) as Catalog;if(!c.catalogId||!Array.isArray(c.cards))return alert('Ungültiger Katalog');state.catalogs.push(c);state.activeCatalogId=c.catalogId;await persist();render();});$<HTMLElement>('[data-reset]')?.addEventListener('click',async()=>{if(!confirm('Alle lokalen Daten löschen?'))return;state=defaultState();await persist();render();});}

async function init(){state=migrate(await loadState(defaultState() as unknown as PersistedState));await persist();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();}
void init();